name: k6 Load Testing

on: [push]

jobs:
  loadTest:
    runs-on: ubuntu-latest
    defaults:
      run:
         working-directory: ./k6-performance-testing
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up k6
      uses: k6io/action@v0.1
      with:
        filename: ./k6-performance-testing/issuesApi.js


    - name: Run k6 test
      run: k6 run -e test_mode=smoke issuesApi.js -e token=${{secrets.PRIVATE_ACCESS_TOKEN}}
